// import './example/basic-type'
// import './example/symbol'
// import './example/interface'
// import './example/function'
// import './example/generics'
// import './example/class'
// import './example/enum'
// import './example/inference-compatibility'
// import './example/advanced-type_1'
// import './example/advanced_type_2'

import './ts-modules/index'
// let num = 1   // Cannot redeclare block-scoped variable 'num'