// import './example/basic-type'
// import './example/symbol'
// import './example/interface'
// import './example/function'
import './example/generics'
// let num = 1   // Cannot redeclare block-scoped variable 'num'